### ISSUE TITLE
[BUG] Crash on startup

### ISSUE THREAD

**Issue by cpawley** [robvdpol/RaceControl#125]
**Describe the bug**
App immediately throws an error and does not load

**To Reproduce**
Launch App

**Expected behavior**
Not to have an error

**Screenshots**
![image](https://user-images.githubusercontent.com/7559173/117534194-ac243d00-aff0-11eb-913f-754826f16ca7.png)

**Desktop (please complete the following information):**
 - Windows edition and version: Windows 10 Home 20H2 
 - System type (32 or 64 bit): 64 bit
 - Version (see title bar): 2.2.0 (issue is not present in 2.0.4)

**F1TV account**
N/A

**Additional context**
Log attached
[RaceControl.log](https://github.com/robvdpol/RaceControl/files/6445603/RaceControl.log)

**Comment by robvdpol** [comment]
@SuRGeoNix this seems to be an NAudio error, do you know what's going on?

2021-05-08 11:25:26.1713 ERROR An unhandled exception occurred.
System.TypeInitializationException: The type initializer for 'FlyleafLib.Master' threw an exception.
 ---> System.Runtime.InteropServices.COMException (0x80070490): Element not found. (0x80070490)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at NAudio.CoreAudioApi.MMDeviceEnumerator.GetDefaultAudioEndpoint(DataFlow dataFlow, Role role)
   at FlyleafLib.AudioMaster.Initialize()
   at FlyleafLib.AudioMaster..ctor()
   at FlyleafLib.Master..cctor()
   --- End of inner exception stack trace ---
   at FlyleafLib.Master.RegisterFFmpeg(String absolutePath, Int32 verbosity)
   at RaceControl.App.Initialize() in D:\Projects\RaceControl\RaceControl\RaceControl\App.xaml.cs:line 63
   at Prism.PrismApplicationBase.InitializeInternal()
   at Prism.PrismApplicationBase.OnStartup(StartupEventArgs e)
   at RaceControl.App.OnStartup(StartupEventArgs e) in D:\Projects\RaceControl\RaceControl\RaceControl\App.xaml.cs:line 56
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by SuRGeoNix** [comment]
It seems that there is no sound card. I will have to review it to allow those cases (with no soundcards)

**Comment by robvdpol** [comment]
Yeah that was my guess as well. @cpawley is that the case?

**Comment by cpawley** [comment]
Uh there is one, but the drivers were not working correctly - when I installed 2.0.4 it was working, but there was no audio - so in short. Yes that matches up with what happened.

I've fixed the problems on my side with the drivers in the meantime - but I guess might be handy to handle the exception for others.

Thanks for the fast reply!

**Comment by robvdpol** [comment]
That makes sense, glad you could fix it.

@SuRGeoNix can you change Flyleaf to handle this exception?

**Comment by SuRGeoNix** [comment]
If I handle would you be able to handle it? :) I mean... you will still enable audio streams... and I guess I should not allow you if there is no sound card. I will have a look but requires testing on pc with no sound card. Need to setup a vm... I will try to include at the next version.

**Comment by robvdpol** [comment]
Hmm, maybe just throw a custom exception that I can catch, so I can display a popup like 'No audio device found' and exit the application.

**Comment by SuRGeoNix** [comment]
I will do it with a property that you will be able to check from AudioMaster which I will also use in the Player to check if I will openaudio or not

**Comment by SuRGeoNix** [comment]
@robvdpol Also from my side currently no audio doesn't make sense and I prefer to avoid it at least for now. Especially for your case I guess you should close this one and I will re-check it in the future.
