### ISSUE TITLE
[BUG]Issue with FlyleafLib on Launch

### ISSUE THREAD

**Issue by PaulDinsdale** [robvdpol/RaceControl#139]
**Describe the bug**
On Launch I get the error "The type initializer for 'FlyleafLib.Master' threw and exception".  Tried on Current version 2.3.0 with installs from both Microsoft store and direct from GitHub,

**Screenshots**
![image](https://user-images.githubusercontent.com/50699767/119261128-f1756c80-bba3-11eb-9ea3-3a8905e5a0f1.png)

**Desktop (please complete the following information):**
Win 10 x64

**Comment by robvdpol** [comment]
Sorry for the late response. Is there a logfile located at **%LOCALAPPDATA%\RaceControl**? If so, could you please paste relevant sections from it here?

**Comment by PaulDinsdale** [comment]
[RaceControl.log](https://github.com/robvdpol/RaceControl/files/6744465/RaceControl.log)


> 2021-06-30 19:26:25.4602 ERROR An unhandled exception occurred.
System.TypeInitializationException: The type initializer for 'FlyleafLib.Master' threw an exception.
 ---> System.Runtime.InteropServices.COMException (0x80070490): Element not found. (0x80070490)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at NAudio.CoreAudioApi.MMDeviceEnumerator.GetDefaultAudioEndpoint(DataFlow dataFlow, Role role)
   at FlyleafLib.AudioMaster.Initialize()
   at FlyleafLib.AudioMaster..ctor()
   at FlyleafLib.Master..cctor()
   --- End of inner exception stack trace ---
   at FlyleafLib.Master.RegisterFFmpeg(String absolutePath, Int32 verbosity)
   at RaceControl.App.Initialize() in D:\Projects\RaceControl\RaceControl\RaceControl\App.xaml.cs:line 63
   at Prism.PrismApplicationBase.InitializeInternal()
   at Prism.PrismApplicationBase.OnStartup(StartupEventArgs e)
   at RaceControl.App.OnStartup(StartupEventArgs e) in D:\Projects\RaceControl\RaceControl\RaceControl\App.xaml.cs:line 56
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by PaulDinsdale** [comment]
Sorry for delay, also new to github, posted the log

**Comment by PaulDinsdale** [comment]
Update on my end, issue caused by not having my headphones plugged in 🤦 

Error clears with some form of speakers/headphones plugged in. Going to close the issue.
