### ISSUE TITLE
[BUG] Live sessions not updating in 2.3.3

### ISSUE THREAD

**Issue by StoobertB** [robvdpol/RaceControl#167]
**Describe the bug**
When starting the application, new sessions are no longer automatically found. Instead I have to click off the current GP (Styrian) and click back on to see the session.

**To Reproduce**
1. Open App
2. Wait for live session to start
3. Notice nothing happens,

**Expected behavior**
An audio sound is played and a session is displayed in the "Live now" pane.

**Desktop (please complete the following information):**
 - Windows 10 Pro x64 running the 20H2 update.
 - 64-bit
 - 2.3.3 Race Control

**F1TV account**
- Subscription type: Pro
- Norway
- Using VPN or proxy? No.

**Additional context**
Trace appears in the log file:

2021-06-26 11:11:51.0158 INFO Querying seasons...
2021-06-26 11:11:51.0158 INFO Querying vod genres...
2021-06-26 11:11:51.1027 INFO Refreshing live sessions...
2021-06-26 11:11:51.1395 INFO Querying live sessions...
2021-06-26 11:11:51.1395 INFO Checking for updates...
2021-06-26 11:11:51.1395 INFO Getting latest release from Github...
2021-06-26 11:11:51.4090 INFO No new release found.
2021-06-26 11:11:51.4240 WARN A non-critical error occurred.
System.NullReferenceException: Object reference not set to an instance of an object.
   at RaceControl.Services.F1TV.ApiService.<>c.<GetLiveSessionsAsync>b__8_4(Container c2) in D:\Projects\RaceControl\RaceControl\Services\RaceControl.Services\F1TV\ApiService.cs:line 87
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at MoreLinq.MoreEnumerable.<>c__DisplayClass43_0`2.<<DistinctBy>g___|0>d.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at RaceControl.Services.F1TV.ApiService.GetLiveSessionsAsync() in D:\Projects\RaceControl\RaceControl\Services\RaceControl.Services\F1TV\ApiService.cs:line 85
   at RaceControl.ViewModels.MainWindowViewModel.RefreshLiveSessionsAsync(Boolean isFirstRefresh) in D:\Projects\RaceControl\RaceControl\RaceControl\ViewModels\MainWindowViewModel.cs:line 769
   at System.Threading.Tasks.TaskExtensions.Await(Task task, Action completedCallback, Action`1 errorCallback, Boolean configureAwait)
2021-06-26 11:11:51.7121 INFO Querying events for season '2021 season'...

**Comment by robvdpol** [comment]
Noticed that yesterday, already fixed it for next release.
