### ISSUE TITLE
[BUG] "The operation has timed out" every time that i try to login

### ISSUE THREAD

**Issue by Dio720** [robvdpol/RaceControl#192]
**F1TV account**
- Subscription type Pro
- Country Brazil
- Using VPN or proxy? No

**Additional context**
Every time that i try to login, says the operation has timed out

**Comment by killyourradio** [comment]
I have experienced the same issue. 

F1TV account

    Subscription type Pro
    Country Germany
    Using VPN or proxy? No

Additional context
Going through the F1TV website works fine. Weirdly enough, using a VPN to connect also works fine. Possibly just something weird in their backend?

**Comment by mufraver2** [comment]
@killyourradio @Dio720 could you paste the log from the time when that error happened? I remember that I had once a problem with login but after a few minutes it started working. Not sure that is it the same problem or not.

I found the log for that:
```
2021-05-08 17:42:19.0555 INFO Sending authorization request for login 'xxx@xxx.com'...
2021-05-08 17:42:19.3969 ERROR Login failed.
System.Net.WebException: No such host is known. (api.formula1.com:443)
 ---> System.Net.Http.HttpRequestException: No such host is known. (api.formula1.com:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at RaceControl.Services.F1TV.AuthorizationService.AuthenticateAsync(String login, String password) in D:\Projects\RaceControl\RaceControl\Services\RaceControl.Services\F1TV\AuthorizationService.cs:line 41
   at RaceControl.ViewModels.LoginDialogViewModel.LoginAsync() in D:\Projects\RaceControl\RaceControl\RaceControl\ViewModels\LoginDialogViewModel.cs:line 80
   at System.Threading.Tasks.TaskExtensionsT.Await[T](Task`1 task, Action`1 completedCallback, Action`1 errorCallback, Boolean configureAwait)
```

**Comment by killyourradio** [comment]
Fairly straightforward timeout:

> 2021-07-30 15:33:31.7552 INFO Settings loaded.
2021-07-30 15:33:31.7958 INFO Video dialog layout loaded.
2021-07-30 15:33:31.7958 WARN Could not find VLC installation.
2021-07-30 15:33:31.7958 INFO Found MPV installation at 'F:\Race Control\mpv\mpv.exe'.
2021-07-30 15:33:31.7958 WARN Could not find MPC-HC installation.
2021-07-30 15:33:31.8564 INFO Credentials loaded from store.
2021-07-30 15:33:31.8564 INFO Sending authorization request for login xxx@xxx.de'...
2021-07-30 15:34:02.0857 ERROR Login failed.
System.Net.WebException: The operation has timed out.
   at RaceControl.Services.F1TV.AuthorizationService.AuthenticateAsync(String login, String password) in D:\Projects\RaceControl\RaceControl\Services\RaceControl.Services\F1TV\AuthorizationService.cs:line 41
   at RaceControl.ViewModels.LoginDialogViewModel.LoginAsync() in D:\Projects\RaceControl\RaceControl\RaceControl\ViewModels\LoginDialogViewModel.cs:line 80
   at System.Threading.Tasks.TaskExtensionsT.Await[T](Task`1 task, Action`1 completedCallback, Action`1 errorCallback, Boolean configureAwait)
2021-07-30 15:34:04.6739 INFO Login cancelled by user, shutting down...
2021-07-30 15:34:04.6969 INFO Settings saved.

Seems to work fine now, so ¯\\\_(ツ)_/¯

**Comment by Romegues** [comment]
I'm having the exact same problem, worked during Monza for some reason but now won't work, the error is:
```
21-09-26 07:20:15.8438 WARN Credentials not found in store.
2021-09-26 07:23:38.2452 INFO Sending authorization request for login 'XXX@xxx.com'...
2021-09-26 07:24:08.3450 ERROR Login failed.
System.Net.WebException: The request timed-out.
   at RaceControl.Services.F1TV.AuthorizationService.AuthenticateAsync(String login, String password) in C:\Github\RaceControl\RaceControl\Services\RaceControl.Services\F1TV\AuthorizationService.cs:line 41
   at RaceControl.ViewModels.LoginDialogViewModel.LoginAsync() in C:\Github\RaceControl\RaceControl\RaceControl\ViewModels\LoginDialogViewModel.cs:line 80
   at System.Threading.Tasks.TaskExtensionsT.Await[T](Task`1 task, Action`1 completedCallback, Action`1 errorCallback, Boolean configureAwait)
```

**Comment by antonpolishko** [comment]
Same issue happens during RussianGP. During Monza everything worked fine

Subscription type Pro
Country US
Using VPN or proxy? No

**Comment by robvdpol** [comment]
Strange that some of you are having this issue, it seems like a fairly straight forward timeout on the F1TV API. Maybe there's some kind of geo restriction at play here?
