### ISSUE TITLE
[BUG] Can't open streams in the internal player.

### ISSUE THREAD

**Issue by Freewarefreak** [robvdpol/RaceControl#197]
**Describe the bug**
Can't open streams in the internal player. All the windows stay white.

**To Reproduce**
1. Go to 'Raceseason 2021.'
2. Play stream 'Monaco grandprix -> race -> worldfeed'
3. Press button 'Watch'
4. See error: No error. Just a blank white screen.
5. Just an example. Happens on ALL.
6. The .NET 5.0 Desktop Runtime (x64) is succesfull installed.

**Expected behavior**
A want to see the stream. 

**Screenshots**
![Screenshot 2021-07-31 163622](https://user-images.githubusercontent.com/88242463/127743621-b7c6f497-b534-4b76-a1a8-47e490bd1c2e.png)
![Screenshot 2021-07-31 163717](https://user-images.githubusercontent.com/88242463/127743626-80837e09-b165-41d9-9310-473555a20d80.png)

**Desktop (please complete the following information):**
 - Windows edition and version: Windows 10 Enterprise
 - System type 64 bit
 - Version 21H1 19043.1110

**F1TV account**
- Subscription type F1TVPro Unlimited
- Country Netherlands
- Using VPN or proxy? No.

**Additional context**
Logfile: 
2021-07-31 15:20:43.0892 INFO Found VLC installation at 'C:\Program Files\VideoLAN\VLC\vlc.exe'.
2021-07-31 15:20:43.1378 INFO Found MPV installation at 'C:\Program Files\Race Control\mpv\mpv.exe'.
2021-07-31 15:20:43.1378 WARN Could not find MPC-HC installation.
2021-07-31 15:20:43.3214 WARN Credentials not found in store.
2021-07-31 15:23:20.1951 INFO Sending authorization request for login 'freewarefreak@hotmail.com'...
2021-07-31 15:23:21.7560 INFO Login successful.
2021-07-31 15:23:21.7795 INFO Credentials saved to store.
2021-07-31 15:23:21.7996 INFO Querying seasons...
2021-07-31 15:23:21.7996 INFO Querying vod genres...
2021-07-31 15:23:21.8310 INFO Refreshing live sessions...
2021-07-31 15:23:21.9456 INFO Querying live sessions...
2021-07-31 15:23:21.9456 INFO Checking for updates...
2021-07-31 15:23:21.9561 INFO Getting latest release from Github...
2021-07-31 15:23:23.2266 INFO Querying events for season '2021 season'...
2021-07-31 15:23:58.7096 INFO Querying sessions for event with UID '1073'...
2021-07-31 15:23:58.7096 INFO Querying episodes for event with UID '1073'...
2021-07-31 15:24:05.9656 INFO Querying channels for session with UID '1000003951'...
2021-07-31 15:24:22.5475 INFO Refreshing live sessions...
2021-07-31 15:24:22.5475 INFO Querying live sessions...
2021-07-31 15:24:33.6387 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?channelId=1009&contentId=1000003951'...
2021-07-31 15:25:20.8485 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?channelId=1004&contentId=1000003951'...
2021-07-31 15:25:22.7848 INFO Refreshing live sessions...
2021-07-31 15:25:22.7848 INFO Querying live sessions...
2021-07-31 15:26:08.8890 WARN A non-critical error occurred.
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at FlyleafLib.Controls.WPF.VideoView.get_Player()
   at FlyleafLib.Controls.WPF.VideoView.Dispose()
   at FlyleafLib.MediaPlayer.Player.DisposeInternal()
   at FlyleafLib.Master.DisposePlayer(Int32 playerId)
   at FlyleafLib.Master.DisposePlayer(Player player)
   at FlyleafLib.MediaPlayer.Player.Dispose()
   at RaceControl.Flyleaf.FlyleafMediaPlayer.<Dispose>b__81_0() in D:\Projects\RaceControl\RaceControl\RaceControl\Flyleaf\FlyleafMediaPlayer.cs:line 276
2021-07-31 15:26:23.0658 INFO Refreshing live sessions...
2021-07-31 15:26:23.0658 INFO Querying live sessions...
2021-07-31 15:26:40.6042 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?channelId=1004&contentId=1000003951'...
2021-07-31 15:26:54.2479 WARN A non-critical error occurred.
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at FlyleafLib.Controls.WPF.VideoView.get_Player()
   at FlyleafLib.Controls.WPF.VideoView.Dispose()
   at FlyleafLib.MediaPlayer.Player.DisposeInternal()
   at FlyleafLib.Master.DisposePlayer(Int32 playerId)
   at FlyleafLib.Master.DisposePlayer(Player player)
   at FlyleafLib.MediaPlayer.Player.Dispose()
   at RaceControl.Flyleaf.FlyleafMediaPlayer.<Dispose>b__81_0() in D:\Projects\RaceControl\RaceControl\RaceControl\Flyleaf\FlyleafMediaPlayer.cs:line 276
2021-07-31 15:27:23.3489 INFO Refreshing live sessions...
2021-07-31 15:27:23.3489 INFO Querying live sessions...
2021-07-31 15:28:03.2893 INFO Querying channels for session with UID '1000003951'...
2021-07-31 15:28:10.5360 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?contentId=1000003951'...
2021-07-31 15:28:23.5654 INFO Refreshing live sessions...
2021-07-31 15:28:23.5654 INFO Querying live sessions...
2021-07-31 15:28:28.9267 INFO Toggling pause...
2021-07-31 15:28:31.4538 INFO Toggling pause...
2021-07-31 15:29:01.6335 WARN A non-critical error occurred.
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at FlyleafLib.Controls.WPF.VideoView.get_Player()
   at FlyleafLib.Controls.WPF.VideoView.Dispose()
   at FlyleafLib.MediaPlayer.Player.DisposeInternal()
   at FlyleafLib.Master.DisposePlayer(Int32 playerId)
   at FlyleafLib.Master.DisposePlayer(Player player)
   at FlyleafLib.MediaPlayer.Player.Dispose()
   at RaceControl.Flyleaf.FlyleafMediaPlayer.<Dispose>b__81_0() in D:\Projects\RaceControl\RaceControl\RaceControl\Flyleaf\FlyleafMediaPlayer.cs:line 276
2021-07-31 15:29:11.1396 INFO Settings saved.
2021-07-31 15:37:10.8820 INFO Settings loaded.
2021-07-31 15:37:10.9402 INFO Found VLC installation at 'C:\Program Files\VideoLAN\VLC\vlc.exe'.
2021-07-31 15:37:10.9402 INFO Found MPV installation at 'C:\Program Files\Race Control\mpv\mpv.exe'.
2021-07-31 15:37:10.9402 WARN Could not find MPC-HC installation.
2021-07-31 15:37:10.9402 INFO Querying seasons...
2021-07-31 15:37:10.9402 INFO Querying vod genres...
2021-07-31 15:37:11.4544 INFO Refreshing live sessions...
2021-07-31 15:37:11.4590 INFO Querying live sessions...
2021-07-31 15:37:11.4590 INFO Checking for updates...
2021-07-31 15:37:11.4590 INFO Getting latest release from Github...
2021-07-31 15:37:12.1422 INFO No new release found.
2021-07-31 15:37:12.7897 INFO Querying events for season '2021 season'...
2021-07-31 15:37:15.4392 INFO Querying channels for session with UID '1000003951'...
2021-07-31 15:37:23.6887 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?contentId=1000003951'...
2021-07-31 15:38:12.1601 INFO Refreshing live sessions...
2021-07-31 15:38:12.1601 INFO Querying live sessions...
2021-07-31 15:38:34.2132 WARN A non-critical error occurred.
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at FlyleafLib.Controls.WPF.VideoView.get_Player()
   at FlyleafLib.Controls.WPF.VideoView.Dispose()
   at FlyleafLib.MediaPlayer.Player.DisposeInternal()
   at FlyleafLib.Master.DisposePlayer(Int32 playerId)
   at FlyleafLib.Master.DisposePlayer(Player player)
   at FlyleafLib.MediaPlayer.Player.Dispose()
   at RaceControl.Flyleaf.FlyleafMediaPlayer.<Dispose>b__81_0() in D:\Projects\RaceControl\RaceControl\RaceControl\Flyleaf\FlyleafMediaPlayer.cs:line 276
2021-07-31 15:39:12.4325 INFO Refreshing live sessions...
2021-07-31 15:39:12.4325 INFO Querying live sessions...
2021-07-31 15:39:57.1461 INFO Settings saved.
2021-07-31 15:40:07.7024 INFO Settings loaded.
2021-07-31 15:40:07.7498 INFO Found VLC installation at 'C:\Program Files\VideoLAN\VLC\vlc.exe'.
2021-07-31 15:40:07.7518 INFO Found MPV installation at 'C:\Program Files\Race Control\mpv\mpv.exe'.
2021-07-31 15:40:07.7518 WARN Could not find MPC-HC installation.
2021-07-31 15:40:07.7518 INFO Querying seasons...
2021-07-31 15:40:07.7518 INFO Querying vod genres...
2021-07-31 15:40:07.9952 INFO Refreshing live sessions...
2021-07-31 15:40:07.9952 INFO Querying live sessions...
2021-07-31 15:40:08.0073 INFO Checking for updates...
2021-07-31 15:40:08.0073 INFO Getting latest release from Github...
2021-07-31 15:40:08.5674 INFO No new release found.
2021-07-31 15:40:09.3799 INFO Querying events for season '2021 season'...
2021-07-31 15:40:11.4077 INFO Querying channels for session with UID '1000003951'...
2021-07-31 15:40:18.9104 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?contentId=1000003951'...
2021-07-31 15:41:08.5789 INFO Refreshing live sessions...
2021-07-31 15:41:08.5789 INFO Querying live sessions...
2021-07-31 15:42:09.2190 INFO Refreshing live sessions...
2021-07-31 15:42:09.2216 INFO Querying live sessions...
2021-07-31 15:43:10.0237 INFO Refreshing live sessions...
2021-07-31 15:43:10.0237 INFO Querying live sessions...
2021-07-31 15:44:10.4740 INFO Refreshing live sessions...
2021-07-31 15:44:10.4740 INFO Querying live sessions...
2021-07-31 15:45:11.4372 INFO Refreshing live sessions...
2021-07-31 15:45:11.4372 INFO Querying live sessions...
2021-07-31 15:46:09.7901 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?channelId=1004&contentId=1000003951'...
2021-07-31 15:46:11.9175 INFO Refreshing live sessions...
2021-07-31 15:46:11.9281 INFO Querying live sessions...
2021-07-31 15:46:45.9222 WARN A non-critical error occurred.
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at FlyleafLib.Controls.WPF.VideoView.get_Player()
   at FlyleafLib.Controls.WPF.VideoView.Dispose()
   at FlyleafLib.MediaPlayer.Player.DisposeInternal()
   at FlyleafLib.Master.DisposePlayer(Int32 playerId)
   at FlyleafLib.Master.DisposePlayer(Player player)
   at FlyleafLib.MediaPlayer.Player.Dispose()
   at RaceControl.Flyleaf.FlyleafMediaPlayer.<Dispose>b__81_0() in D:\Projects\RaceControl\RaceControl\RaceControl\Flyleaf\FlyleafMediaPlayer.cs:line 276
2021-07-31 15:46:55.9773 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?channelId=1004&contentId=1000003951'...
2021-07-31 15:47:12.7108 INFO Refreshing live sessions...
2021-07-31 15:47:12.7108 INFO Querying live sessions...
2021-07-31 15:48:13.1633 INFO Refreshing live sessions...
2021-07-31 15:48:13.1633 INFO Querying live sessions...
2021-07-31 15:49:13.3754 INFO Refreshing live sessions...
2021-07-31 15:49:13.3754 INFO Querying live sessions...
2021-07-31 15:50:13.5937 INFO Refreshing live sessions...
2021-07-31 15:50:13.5937 INFO Querying live sessions...
2021-07-31 15:50:42.2755 INFO Settings saved.
2021-07-31 15:51:19.7603 INFO Settings loaded.
2021-07-31 15:51:19.7958 INFO Found VLC installation at 'C:\Program Files\VideoLAN\VLC\vlc.exe'.
2021-07-31 15:51:19.7958 INFO Found MPV installation at 'C:\Program Files\Race Control\mpv\mpv.exe'.
2021-07-31 15:51:19.7958 WARN Could not find MPC-HC installation.
2021-07-31 15:51:19.8044 INFO Querying seasons...
2021-07-31 15:51:19.8044 INFO Querying vod genres...
2021-07-31 15:51:20.4126 INFO Refreshing live sessions...
2021-07-31 15:51:20.4126 INFO Querying live sessions...
2021-07-31 15:51:20.4246 INFO Checking for updates...
2021-07-31 15:51:20.4246 INFO Getting latest release from Github...
2021-07-31 15:51:20.7813 INFO No new release found.
2021-07-31 15:51:21.3022 INFO Querying events for season '2021 season'...
2021-07-31 15:51:23.3996 INFO Querying channels for session with UID '1000003951'...
2021-07-31 15:52:20.8968 INFO Refreshing live sessions...
2021-07-31 15:52:20.8968 INFO Querying live sessions...
2021-07-31 15:52:32.9021 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?channelId=1009&contentId=1000003951'...
2021-07-31 15:53:21.1742 INFO Refreshing live sessions...
2021-07-31 15:53:21.1742 INFO Querying live sessions...
2021-07-31 15:53:40.5495 WARN A non-critical error occurred.
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at FlyleafLib.Controls.WPF.VideoView.get_Player()
   at FlyleafLib.Controls.WPF.VideoView.Dispose()
   at FlyleafLib.MediaPlayer.Player.DisposeInternal()
   at FlyleafLib.Master.DisposePlayer(Int32 playerId)
   at FlyleafLib.Master.DisposePlayer(Player player)
   at FlyleafLib.MediaPlayer.Player.Dispose()
   at RaceControl.Flyleaf.FlyleafMediaPlayer.<Dispose>b__81_0() in D:\Projects\RaceControl\RaceControl\RaceControl\Flyleaf\FlyleafMediaPlayer.cs:line 276
2021-07-31 15:53:53.6691 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?channelId=1009&contentId=1000003951'...
2021-07-31 15:54:21.4392 INFO Refreshing live sessions...
2021-07-31 15:54:21.4392 INFO Querying live sessions...
2021-07-31 15:54:46.8126 INFO Settings saved.
2021-07-31 15:58:26.2233 INFO Settings loaded.
2021-07-31 15:58:26.2612 INFO Found VLC installation at 'C:\Program Files\VideoLAN\VLC\vlc.exe'.
2021-07-31 15:58:26.2612 INFO Found MPV installation at 'C:\Program Files\Race Control\mpv\mpv.exe'.
2021-07-31 15:58:26.2682 WARN Could not find MPC-HC installation.
2021-07-31 15:58:26.2682 INFO Querying seasons...
2021-07-31 15:58:26.2871 INFO Querying vod genres...
2021-07-31 15:58:26.5591 INFO Refreshing live sessions...
2021-07-31 15:58:26.5669 INFO Querying live sessions...
2021-07-31 15:58:26.5823 INFO Checking for updates...
2021-07-31 15:58:26.5823 INFO Getting latest release from Github...
2021-07-31 15:58:26.8640 INFO No new release found.
2021-07-31 15:58:27.6252 INFO Querying events for season '2021 season'...
2021-07-31 15:59:27.0628 INFO Refreshing live sessions...
2021-07-31 15:59:27.0628 INFO Querying live sessions...
2021-07-31 15:59:47.9909 INFO Querying channels for session with UID '1000003951'...
2021-07-31 15:59:53.9948 INFO Settings saved.
2021-07-31 16:21:37.8895 INFO Settings loaded.
2021-07-31 16:21:37.9234 INFO Found VLC installation at 'C:\Program Files\VideoLAN\VLC\vlc.exe'.
2021-07-31 16:21:37.9254 INFO Found MPV installation at 'C:\Program Files\Race Control\mpv\mpv.exe'.
2021-07-31 16:21:37.9254 WARN Could not find MPC-HC installation.
2021-07-31 16:21:37.9254 INFO Querying seasons...
2021-07-31 16:21:37.9254 INFO Querying vod genres...
2021-07-31 16:21:38.1177 INFO Refreshing live sessions...
2021-07-31 16:21:38.1177 INFO Querying live sessions...
2021-07-31 16:21:38.1298 INFO Checking for updates...
2021-07-31 16:21:38.1298 INFO Getting latest release from Github...
2021-07-31 16:21:38.3279 INFO No new release found.
2021-07-31 16:21:39.0072 INFO Querying events for season '2021 season'...
2021-07-31 16:22:38.4867 INFO Refreshing live sessions...
2021-07-31 16:22:38.4867 INFO Querying live sessions...
2021-07-31 16:23:38.7167 INFO Refreshing live sessions...
2021-07-31 16:23:38.7211 INFO Querying live sessions...
2021-07-31 16:24:38.9376 INFO Refreshing live sessions...
2021-07-31 16:24:38.9376 INFO Querying live sessions...
2021-07-31 16:25:39.1463 INFO Refreshing live sessions...
2021-07-31 16:25:39.1463 INFO Querying live sessions...
2021-07-31 16:26:39.3481 INFO Refreshing live sessions...
2021-07-31 16:26:39.3481 INFO Querying live sessions...
2021-07-31 16:26:51.3634 INFO Querying sessions for event with UID '1073'...
2021-07-31 16:26:51.3634 INFO Querying episodes for event with UID '1073'...
2021-07-31 16:26:54.0064 INFO Querying channels for session with UID '1000003951'...
2021-07-31 16:27:02.7680 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?contentId=1000003951'...
2021-07-31 16:27:11.8570 WARN A non-critical error occurred.
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at FlyleafLib.Controls.WPF.VideoView.get_Player()
   at FlyleafLib.Controls.WPF.VideoView.Dispose()
   at FlyleafLib.MediaPlayer.Player.DisposeInternal()
   at FlyleafLib.Master.DisposePlayer(Int32 playerId)
   at FlyleafLib.Master.DisposePlayer(Player player)
   at FlyleafLib.MediaPlayer.Player.Dispose()
   at RaceControl.Flyleaf.FlyleafMediaPlayer.<Dispose>b__81_0() in D:\Projects\RaceControl\RaceControl\RaceControl\Flyleaf\FlyleafMediaPlayer.cs:line 276
2021-07-31 16:27:13.3061 INFO Querying channels for session with UID '1000003948'...
2021-07-31 16:27:18.3957 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?contentId=1000003948'...
2021-07-31 16:27:26.7656 WARN A non-critical error occurred.
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at FlyleafLib.Controls.WPF.VideoView.get_Player()
   at FlyleafLib.Controls.WPF.VideoView.Dispose()
   at FlyleafLib.MediaPlayer.Player.DisposeInternal()
   at FlyleafLib.Master.DisposePlayer(Int32 playerId)
   at FlyleafLib.Master.DisposePlayer(Player player)
   at FlyleafLib.MediaPlayer.Player.Dispose()
   at RaceControl.Flyleaf.FlyleafMediaPlayer.<Dispose>b__81_0() in D:\Projects\RaceControl\RaceControl\RaceControl\Flyleaf\FlyleafMediaPlayer.cs:line 276
2021-07-31 16:27:30.6818 INFO Querying episodes for vod genre 'Best Onboards'...
2021-07-31 16:27:38.1800 INFO Getting tokenised URL for content-type 'Asset' and content-URL 'CONTENT/PLAY?contentId=1000004545'...
2021-07-31 16:27:39.5671 INFO Refreshing live sessions...
2021-07-31 16:27:39.5671 INFO Querying live sessions...
2021-07-31 16:27:49.3663 WARN A non-critical error occurred.
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at FlyleafLib.Controls.WPF.VideoView.get_Player()
   at FlyleafLib.Controls.WPF.VideoView.Dispose()
   at FlyleafLib.MediaPlayer.Player.DisposeInternal()
   at FlyleafLib.Master.DisposePlayer(Int32 playerId)
   at FlyleafLib.Master.DisposePlayer(Player player)
   at FlyleafLib.MediaPlayer.Player.Dispose()
   at RaceControl.Flyleaf.FlyleafMediaPlayer.<Dispose>b__81_0() in D:\Projects\RaceControl\RaceControl\RaceControl\Flyleaf\FlyleafMediaPlayer.cs:line 276
2021-07-31 16:27:53.4518 INFO Getting tokenised URL for content-type 'Asset' and content-URL 'CONTENT/PLAY?contentId=1000004545'...
2021-07-31 16:28:39.7419 INFO Refreshing live sessions...
2021-07-31 16:28:39.7419 INFO Querying live sessions...
2021-07-31 16:28:48.9158 INFO Getting tokenised URL for content-type 'Asset' and content-URL 'CONTENT/PLAY?contentId=1000004545'...
2021-07-31 16:29:26.0719 INFO Getting tokenised URL for content-type 'Asset' and content-URL 'CONTENT/PLAY?contentId=1000004545'...
2021-07-31 16:29:40.0339 INFO Refreshing live sessions...
2021-07-31 16:29:40.0339 INFO Querying live sessions...
2021-07-31 16:29:56.2633 INFO Toggling pause...
2021-07-31 16:29:57.1269 INFO Toggling pause...
2021-07-31 16:30:35.4068 INFO Toggling pause...
2021-07-31 16:30:36.7507 INFO Toggling pause...
2021-07-31 16:30:40.2084 INFO Refreshing live sessions...
2021-07-31 16:30:40.2084 INFO Querying live sessions...
2021-07-31 16:31:05.0774 WARN A non-critical error occurred.
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at FlyleafLib.Controls.WPF.VideoView.get_Player()
   at FlyleafLib.Controls.WPF.VideoView.Dispose()
   at FlyleafLib.MediaPlayer.Player.DisposeInternal()
   at FlyleafLib.Master.DisposePlayer(Int32 playerId)
   at FlyleafLib.Master.DisposePlayer(Player player)
   at FlyleafLib.MediaPlayer.Player.Dispose()
   at RaceControl.Flyleaf.FlyleafMediaPlayer.<Dispose>b__81_0() in D:\Projects\RaceControl\RaceControl\RaceControl\Flyleaf\FlyleafMediaPlayer.cs:line 276
2021-07-31 16:31:40.3965 INFO Refreshing live sessions...
2021-07-31 16:31:40.3965 INFO Querying live sessions...
2021-07-31 16:32:40.5883 INFO Refreshing live sessions...
2021-07-31 16:32:40.5883 INFO Querying live sessions...
2021-07-31 16:33:40.7879 INFO Refreshing live sessions...
2021-07-31 16:33:40.7879 INFO Querying live sessions...
2021-07-31 16:34:06.7618 INFO Settings loaded.
2021-07-31 16:34:06.7922 INFO Found VLC installation at 'C:\Program Files\VideoLAN\VLC\vlc.exe'.
2021-07-31 16:34:06.7922 INFO Found MPV installation at 'C:\Program Files\Race Control\mpv\mpv.exe'.
2021-07-31 16:34:06.7922 WARN Could not find MPC-HC installation.
2021-07-31 16:34:06.7922 INFO Querying seasons...
2021-07-31 16:34:06.7922 INFO Querying vod genres...
2021-07-31 16:34:06.9520 INFO Refreshing live sessions...
2021-07-31 16:34:06.9520 INFO Querying live sessions...
2021-07-31 16:34:06.9520 INFO Checking for updates...
2021-07-31 16:34:06.9636 INFO Getting latest release from Github...
2021-07-31 16:34:07.2522 INFO No new release found.
2021-07-31 16:34:07.7417 INFO Querying events for season '2021 season'...
2021-07-31 16:34:15.9749 INFO Settings saved.
2021-07-31 16:34:23.2160 INFO Querying sessions for event with UID '1073'...
2021-07-31 16:34:23.2160 INFO Querying episodes for event with UID '1073'...
2021-07-31 16:34:25.6012 INFO Querying channels for session with UID '1000003951'...
2021-07-31 16:34:37.8741 INFO Querying events for season '2018 season'...
2021-07-31 16:34:39.7444 INFO Querying sessions for event with UID '988'...
2021-07-31 16:34:39.7480 INFO Querying episodes for event with UID '988'...
2021-07-31 16:34:40.9784 INFO Refreshing live sessions...
2021-07-31 16:34:40.9784 INFO Querying live sessions...
2021-07-31 16:34:42.3988 INFO Querying channels for session with UID '1000002436'...
2021-07-31 16:34:46.2406 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?contentId=1000002436'...
2021-07-31 16:35:21.9893 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?contentId=1000002436'...
2021-07-31 16:35:41.1584 INFO Refreshing live sessions...
2021-07-31 16:35:41.1584 INFO Querying live sessions...
2021-07-31 16:36:32.3590 WARN A non-critical error occurred.
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at FlyleafLib.Controls.WPF.VideoView.get_Player()
   at FlyleafLib.Controls.WPF.VideoView.Dispose()
   at FlyleafLib.MediaPlayer.Player.DisposeInternal()
   at FlyleafLib.Master.DisposePlayer(Int32 playerId)
   at FlyleafLib.Master.DisposePlayer(Player player)
   at FlyleafLib.MediaPlayer.Player.Dispose()
   at RaceControl.Flyleaf.FlyleafMediaPlayer.<Dispose>b__81_0() in D:\Projects\RaceControl\RaceControl\RaceControl\Flyleaf\FlyleafMediaPlayer.cs:line 276
2021-07-31 16:36:36.2615 INFO Querying events for season '2021 season'...
2021-07-31 16:36:38.9221 INFO Querying sessions for event with UID '1067'...
2021-07-31 16:36:38.9221 INFO Querying episodes for event with UID '1067'...
2021-07-31 16:36:41.3548 INFO Refreshing live sessions...
2021-07-31 16:36:41.3548 INFO Querying live sessions...
2021-07-31 16:36:42.0674 INFO Querying channels for session with UID '1000003922'...
2021-07-31 16:36:48.2876 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?contentId=1000003922'...
2021-07-31 16:37:23.4847 WARN A non-critical error occurred.
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at FlyleafLib.Controls.WPF.VideoView.get_Player()
   at FlyleafLib.Controls.WPF.VideoView.Dispose()
   at FlyleafLib.MediaPlayer.Player.DisposeInternal()
   at FlyleafLib.Master.DisposePlayer(Int32 playerId)
   at FlyleafLib.Master.DisposePlayer(Player player)
   at FlyleafLib.MediaPlayer.Player.Dispose()
   at RaceControl.Flyleaf.FlyleafMediaPlayer.<Dispose>b__81_0() in D:\Projects\RaceControl\RaceControl\RaceControl\Flyleaf\FlyleafMediaPlayer.cs:line 276
2021-07-31 16:37:24.8273 INFO Querying channels for session with UID '1000004315'...
2021-07-31 16:37:25.3634 INFO Querying channels for session with UID '1000003922'...
2021-07-31 16:37:28.8741 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?contentId=1000003922'...
2021-07-31 16:37:41.5518 INFO Refreshing live sessions...
2021-07-31 16:37:41.5518 INFO Querying live sessions...

**Comment by Freewarefreak** [comment]
Why does nobody reply?

**Comment by robvdpol** [comment]
I just became a father last week so I can't spend much time on Race Control right now. I'll be back soon though.

**Comment by Freewarefreak** [comment]
Thank you Rob, enjoy your newborn :) I will patiently wait. :)

**Comment by mufraver2** [comment]
For me it's working normally. Tried to reproduce that but I wasn't able. I also noticed that I have that same exception coming from the Flyleaf library in my log but everything seems to be working.

@Freewarefreak Do you happen to have another PC around if you could try it with that?

**Comment by robvdpol** [comment]
Possibly solved in upcoming release, please report back if it still doesn't work.

**Comment by Freewarefreak** [comment]
hi Rob,

thx for your effort. i will update and test and feedback.

kind regards

Edwin

________________________________
