### ISSUE TITLE
[BUG] The type initializer for FlyleafLib.Master threw an exception

### ISSUE THREAD

**Issue by michelderooij** [robvdpol/RaceControl#214]
Starting RC Control 2.3.5 after installing requirements (NET 5 etc) on W11 x64.
RC logo shows, then error is thrown and world stops turning. RC logo stays on screen (have to kill the task).

Reproduce:
- Install prereqs, eg NET Runtime v5.0.9
- Start RC 2.3.5.0

Windows 11 x64 build v10.0.22000.160
F1TV subscription (via Ziggo)
NL

RaceControl.log:
2021-08-27 17:47:13.4668 ERROR An unhandled exception occurred.
System.TypeInitializationException: The type initializer for 'FlyleafLib.Master' threw an exception.
 ---> System.InvalidCastException: Specified cast is not valid.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at NAudio.CoreAudioApi.AudioSessionManager.RefreshSessions()
   at NAudio.CoreAudioApi.AudioSessionManager..ctor(IAudioSessionManager audioSessionManager)
   at NAudio.CoreAudioApi.MMDevice.GetAudioSessionManager()
   at FlyleafLib.AudioMaster.Initialize()
   at FlyleafLib.AudioMaster..ctor()
   at FlyleafLib.Master..cctor()
   --- End of inner exception stack trace ---
   at FlyleafLib.Master.RegisterFFmpeg(String absolutePath, Int32 verbosity)
   at RaceControl.App.Initialize() in D:\Projects\RaceControl\RaceControl\RaceControl\App.xaml.cs:line 63
   at Prism.PrismApplicationBase.InitializeInternal()
   at Prism.PrismApplicationBase.OnStartup(StartupEventArgs e)
   at RaceControl.App.OnStartup(StartupEventArgs e) in D:\Projects\RaceControl\RaceControl\RaceControl\App.xaml.cs:line 56
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by SuRGeoNix** [comment]
Do you have any audio devices?

**Comment by michelderooij** [comment]
Built-in (Conexant, it's a laptop). Also set this as default device as I have Jabra headset which dongle I unplugged to see if it had any effect looking at the bluetooth-related/audio reports.

**Comment by michelderooij** [comment]
Suspecting the Conexant driver; have no audio on Ziggo app as well. Will look for rollback or other set - will update later.

**Comment by michelderooij** [comment]
Installed old W10 driver over the built-in W11 one. Works now - apparent driver issue, so closed this one.
