### ISSUE TITLE
[BUG] 2021 Belgian Grand Prix Free Practice 3 not playing or downloading

### ISSUE THREAD

**Issue by LuckyRed93** [robvdpol/RaceControl#218]
**Describe the bug**
Unable to play or to download any of the feeds from FP3 of the 2021 Belgian Grand Prix.

**Screenshots**
![2021-09-01 (1)](https://user-images.githubusercontent.com/85454253/131633084-865ed4f3-3b80-4472-a3d2-ffb598c978ed.png)

**Desktop (please complete the following information):**
 - Windows 10 Home 21H1 64 bit
 - Race Control 2.3.5

**Additional context**
2021-09-01 09:47:19.7668 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?contentId=1000003955'...
2021-09-01 09:47:21.6117 ERROR A critical error occurred.
System.Exception: An error occurred while opening the stream URL (error code: -858797304).
   at RaceControl.Flyleaf.FlyleafMediaDownloader.<>c__DisplayClass12_0.<StartDownloadAsync>b__0() in D:\Projects\RaceControl\RaceControl\RaceControl\Flyleaf\FlyleafMediaDownloader.cs:line 51
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at RaceControl.ViewModels.DownloadDialogViewModel.StartDownloadAsync() in D:\Projects\RaceControl\RaceControl\RaceControl\ViewModels\DownloadDialogViewModel.cs:line 66
   at System.Threading.Tasks.TaskExtensions.Await(Task task, Action completedCallback, Action`1 errorCallback, Boolean configureAwait)

The same error code appears on every feed of that session.

**Comment by robvdpol** [comment]
Should be fixed in upcoming release.
