### ISSUE TITLE
Facing issue to start stream

### ISSUE THREAD

**Issue by Shantanu260696** [robvdpol/RaceControl#333]
i see the attached issue when i click on watch
![Git cap](https://user-images.githubusercontent.com/101323943/157630980-d24c138e-7f90-4ff8-b2be-46c48fcf851c.JPG)

**Comment by mudux** [comment]
Facing similar problem

My log below:
### 
```
2022-03-10 12:44:36.5520 INFO Refreshing live sessions...
2022-03-10 12:44:36.5520 INFO Querying live sessions...
2022-03-10 12:45:47.6965 INFO Refreshing live sessions...
2022-03-10 12:45:47.6965 INFO Querying live sessions...
2022-03-10 12:45:50.1182 INFO Settings saved.
2022-03-10 14:14:47.4431 INFO Settings loaded.
2022-03-10 14:14:47.5043 INFO Found VLC installation at 'C:\Program Files\VideoLAN\VLC\vlc.exe'.
2022-03-10 14:14:47.5043 INFO Found MPV installation at 'C:\Program Files\WindowsApps\16380RobvanderPol.F1RaceControl_2.3.4.0_x64__2z9spsj1fgqzr\RaceControl\mpv\mpv.exe'.
2022-03-10 14:14:47.5043 WARN Could not find MPC-HC installation.
2022-03-10 14:14:47.5347 INFO Querying seasons...
2022-03-10 14:14:47.5455 INFO Querying vod genres...
2022-03-10 14:14:47.9240 INFO Refreshing live sessions...
2022-03-10 14:14:47.9240 INFO Querying live sessions...
2022-03-10 14:14:47.9471 INFO Checking for updates...
2022-03-10 14:14:47.9504 INFO Getting latest release from Github...
2022-03-10 14:14:49.2381 INFO No new release found.
2022-03-10 14:14:53.0468 INFO Querying events for season '2022 season'...
2022-03-10 14:15:49.4371 INFO Refreshing live sessions...
2022-03-10 14:15:49.4371 INFO Querying live sessions...
2022-03-10 14:15:55.8726 INFO Querying sessions for event with UID '1123'...
2022-03-10 14:15:55.8912 INFO Querying episodes for event with UID '1123'...
2022-03-10 14:15:58.9646 INFO Querying sessions for event with UID '1132'...
2022-03-10 14:15:58.9646 INFO Querying episodes for event with UID '1132'...
2022-03-10 14:16:02.0555 INFO Querying channels for session with UID '1000005273'...
2022-03-10 14:16:06.7425 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?contentId=1000005273'...
2022-03-10 14:16:10.7387 ERROR A critical error occurred.
System.Exception: An error occurred while retrieving the stream URL.
   at RaceControl.ViewModels.VideoDialogViewModel.StartStreamAsync()
   at System.Threading.Tasks.TaskExtensions.Await(Task task, Action completedCallback, Action`1 errorCallback, Boolean configureAwait)
```

**Comment by Edivad99** [comment]
Do you have F1 tv access or pro?
In India, you can only have F1 Tv Access and some content is not visible. I have also found it that I live in Italy. The application does not tell you that those contents are not available in your subscription

**Comment by mudux** [comment]
I have pro..

The issue is resolved by logging out and logging back in.

Must be a bug.

**Comment by Edivad99** [comment]
Okay, we should still implement some kind of icon that indicates what content is only available for F1 TV PRO

**Comment by robvdpol** [comment]
It's difficult since it depends on the region of the user. F1TV Access has different content in different parts of the world.

**Comment by Edivad99** [comment]
I think I saw in the JSON, some fields that said what subscription you need to have to see the video. We could use the JWT and see if the user has permissions to view.
Or perhaps use the response header to give a clearer message to the user.
