### ISSUE TITLE
[BUG] An error occurred while retreiving the stream URL.

### ISSUE THREAD

**Issue by liquidacid** [robvdpol/RaceControl#343]
**Describe the bug**
I can't start any streams or download streams (last will crash RC and leaves no log)

**To Reproduce**
2. Play stream '...'

Above does trigger it

**Expected behavior**
Play the stream

**Screenshots**

**Desktop (please complete the following information):**
Editie	Windows 10 Pro
Versie	20H2
Installatiedatum	‎7-‎12-‎2020
Build van besturingssysteem	19042.1586
Ervaring	Windows Feature Experience Pack 120.2212.4170.0
64 bit

**F1TV account**
- Subscription type: **Pro**
- Country: **NL** 
- Using VPN or proxy? **No**

**Additional context**
`2022-03-15 11:09:21.3923 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?contentId=1000005440'...
2022-03-15 11:09:21.5908 ERROR A critical error occurred.
System.Exception: An error occurred while retrieving the stream URL.
   at RaceControl.ViewModels.VideoDialogViewModel.StartStreamAsync()
   at System.Threading.Tasks.TaskExtensions.Await(Task task, Action completedCallback, Action`1 errorCallback, Boolean configureAwait)
2022-03-15 11:09:24.2715 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?contentId=1000005440'...
2022-03-15 11:09:24.4022 ERROR A critical error occurred.
System.Exception: An error occurred while retrieving the stream URL.
   at RaceControl.ViewModels.MainWindowViewModel.ValidateStreamUrl(String streamUrl)
   at RaceControl.ViewModels.MainWindowViewModel.WatchInVlcAsync(IPlayableContent playableContent)
   at System.Threading.Tasks.TaskExtensions.Await(Task task, Action completedCallback, Action`1 errorCallback, Boolean configureAwait)`

**Comment by timfrankentwf** [comment]
Which content are you trying to play? And which version are you running?

**Comment by timfrankentwf** [comment]
Can you check if this solved your issue?
