### ISSUE TITLE
[BUG] Chromecast load failed

### ISSUE THREAD

**Issue by tomnokoe** [robvdpol/RaceControl#347]
**Describe the bug**
Load failed when attempting to cast, very similar to https://github.com/robvdpol/RaceControl/issues/258

**Desktop (please complete the following information):**
 - Windows 10
 - 64bit
 - 21H2

**F1TV account**
- Subscription type PRO
- Country UK
- Using VPN or proxy? VPN

[Load failed error log.txt](https://github.com/robvdpol/RaceControl/files/8257931/Load.failed.error.log.txt)

**Comment by robvdpol** [comment]
I'll have to check, maybe they changed something again :/

**Comment by Justmie** [comment]
Doesn't happen on the "old" Chromecast 2018 (non ultra). 

Desktop

Windows 10
64bit
21H1
F1TV account

Subscription type PRO
Country NL
Using VPN or proxy? Nope

**Comment by robvdpol** [comment]
Works fine on my Chromecast Ultra as well. Which version of Race Control are you using?

**Comment by FinnBerkers** [comment]
Happens for me as well on a 2020 Chormecast with android TV.
it just doesn't see the chomecast while google chrome (the browser) on the same device can connect to it fine.

the Race Control version is 2.6.0.

Desktop

Windows 10
64bit
Unsure?
F1TV account

Subscription type PRO
Country NL
Using VPN or proxy? Nope

**Comment by robvdpol** [comment]
@FinnBerkers That's a different issue. Did you select the right network interface in the dropdown box? Not much I can do about it otherwise, probably some network issue that Googlecast library doesn't support.

**Comment by FinnBerkers** [comment]
@robvdpol Yes I did test all of the different Network interfaces (even though it defaulted to the one I'm actively using) but it only showed the loading icon on one of them and then nothing more happened.
I am new to this amazing piece of software so I'm not sure what's supposed to happen, but there's something right?

**Comment by FinnBerkers** [comment]
@robvdpol So the issue was that there was a windows update from before the release of the latest version of Race Control which I hadn't installed yet... did that and all worked perfectly.

**Comment by Qkev** [comment]
Same issue here!

**Comment by DaanSchuitmaker** [comment]
Still getting load failed.

RC Version: 2.6.4

`2022-04-22 13:19:32.0829 ERROR A critical error occurred.
System.Exception: Load failed
   at GoogleCast.Messages.Media.LoadFailedMessage.OnDeserializing(StreamingContext context)
   at ReadLoadFailedMessageFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.InternalReadObject(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(Stream stream)
   at GoogleCast.JsonSerializer.Deserialize(Type type, Byte[] str)
   at GoogleCast.Sender.<>c__DisplayClass44_0.<<Receive>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at GoogleCast.TaskExtensions.TimeoutAfter[T](Task`1 task, Int32 delay)
   at GoogleCast.Sender.SendAsync[TResponse](String ns, IMessageWithId message, String destinationId)
   at GoogleCast.Channels.Channel.SendAsync[TResponse](IMessageWithId message, String destinationId)
   at GoogleCast.Channels.MediaChannel.SendAsync(IMessageWithId message)
   at GoogleCast.Channels.MediaChannel.LoadAsync(MediaInformation media, Boolean autoPlay, Int32[] activeTrackIds)
   at RaceControl.ViewModels.MainWindowViewModel.CastContentAsync(IReceiver receiver, IPlayableContent playableContent) in D:\Projects\RaceControl\RaceControl\RaceControl\ViewModels\MainWindowViewModel.cs:line 1024
   at System.Threading.Tasks.TaskExtensions.Await(Task task, Action completedCallback, Action`1 errorCallback, Boolean configureAwait)
`

**Comment by DaanSchuitmaker** [comment]
@robvdpol what data do you need to resolve this.
It wasn't a problem before F1 tv started to use DRM and stuff
