### ISSUE TITLE
Start a live channel initially fails while existing channels start-up fine. 

### ISSUE THREAD

**Issue by RoKaWaTv** [robvdpol/RaceControl#437]
**Describe the bug**
On my labtop , yesterday (april 24) around 1830 hrs try to start live channel of f1 race, but only blurred image and no sound. Same time tried existing channel (f1 Sprint of april 23) and that worked properly.  Tried several times with MPV and WATCH button
Switched to a tablet at 1835 hrs and started the F1 pro app. That immediate worked fine.
Later around 2000 hrs I tried the Race Control on my labtop again and it immediate worked fine and could watch the rest of the f1 race stream perfectly without any issue, exept the fine quality and possibilities of the race control app!

**To Reproduce**
Not something specific

**Expected behavior**
A proper working live stream as from the moment I started the F1 live channel

**Screenshots**
The screen was blurred with several colours and no sound

**Desktop (please complete the following information):**
 - Windows edition and version
Editie	Windows 11 Home Versie	21H2
Installatiedatum	‎14-‎12-‎2021  Build van besturingssysteem	22000.613
Serienummer	YD06EFG8 Ervaring	Windows Feature Experience Pack 1000.22000.613.0
 - System type 64 bit 
- Version (2.6.4)

**F1TV account**
- Subscription type Pro
- Country NL
- Using VPN or proxy? Nope

**Additional context**
Copy of the log file;
quote
2022-04-24 09:17:26.8317 INFO Getting tokenised URL for content-type 'Asset' and content-URL 'CONTENT/PLAY?contentId=1000005666'...
2022-04-24 09:18:21.9597 INFO Getting tokenised URL for content-type 'Asset' and content-URL 'CONTENT/PLAY?contentId=1000005662'...
2022-04-24 09:18:51.5534 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?channelId=1033&contentId=1000005118'...
2022-04-24 09:18:52.4273 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?channelId=1033&contentId=1000005118'...
2022-04-24 09:18:52.6694 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?channelId=1033&contentId=1000005118'...
2022-04-24 09:21:59.9960 INFO Querying channels for session with UID '1000005117'...
2022-04-24 09:22:05.4778 INFO Querying channels for session with UID '1000005579'...
2022-04-24 09:22:24.9334 INFO Querying channels for session with UID '1000005580'...
2022-04-24 09:22:26.8526 INFO Querying channels for session with UID '1000005116'...
2022-04-24 09:22:42.8922 INFO Querying channels for session with UID '1000005124'...
2022-04-24 09:22:46.3103 INFO Querying channels for session with UID '1000005117'...
2022-04-24 18:19:49.3511 INFO Settings saved.
2022-04-24 18:20:41.8803 INFO Settings loaded.
2022-04-24 18:20:41.9261 WARN Could not find VLC installation.
2022-04-24 18:20:41.9261 INFO Found MPV installation at 'C:\Users\ronald\Downloads\RaceControl_2.6.4_x64_portable\mpv\mpv.exe'.
2022-04-24 18:20:41.9261 WARN Could not find MPC-HC installation.
2022-04-24 18:20:41.9261 INFO Querying seasons...
2022-04-24 18:20:41.9674 INFO Querying vod genres...
2022-04-24 18:20:42.0991 INFO Refreshing live sessions...
2022-04-24 18:20:42.0991 INFO Querying live sessions...
2022-04-24 18:20:42.0991 INFO Checking for updates...
2022-04-24 18:20:42.0991 INFO Getting latest release from GitHub...
2022-04-24 18:20:42.6679 INFO No new release found.
2022-04-24 18:20:43.0525 INFO Querying events for season '2022 season'...
2022-04-24 18:20:43.1792 INFO Querying sessions for event with UID '1109'...
2022-04-24 18:20:43.1792 INFO Querying episodes for event with UID '1109'...
2022-04-24 18:21:00.4051 INFO Querying channels for session with UID '1000005123'...
2022-04-24 18:21:16.7905 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?channelId=1033&contentId=1000005123'...
2022-04-24 18:21:42.7556 INFO Refreshing live sessions...
2022-04-24 18:21:42.7556 INFO Querying live sessions...
2022-04-24 18:22:42.9730 INFO Refreshing live sessions...
2022-04-24 18:22:42.9730 INFO Querying live sessions...
2022-04-24 18:23:43.2139 INFO Refreshing live sessions...
2022-04-24 18:23:43.2139 INFO Querying live sessions...
2022-04-24 18:24:15.6890 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?channelId=1033&contentId=1000005123'...
2022-04-24 18:24:16.9566 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?channelId=1033&contentId=1000005123'...
2022-04-24 18:24:43.4911 INFO Refreshing live sessions...
2022-04-24 18:24:43.4911 INFO Querying live sessions...
2022-04-24 18:25:43.7235 INFO Refreshing live sessions...
2022-04-24 18:25:43.7235 INFO Querying live sessions...
2022-04-24 18:26:43.9254 INFO Refreshing live sessions...
2022-04-24 18:26:43.9254 INFO Querying live sessions...
2022-04-24 18:27:44.1616 INFO Refreshing live sessions...
2022-04-24 18:27:44.1616 INFO Querying live sessions...
2022-04-24 18:28:44.3564 INFO Refreshing live sessions...
2022-04-24 18:28:44.3564 INFO Querying live sessions...
2022-04-24 18:29:44.5993 INFO Refreshing live sessions...
2022-04-24 18:29:44.5993 INFO Querying live sessions...
2022-04-24 18:29:45.4292 WARN A non-critical error occurred.
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: Unable to read data from the transport connection: De externe host heeft een verbinding verbroken..
 ---> System.Net.Sockets.SocketException (10054): De externe host heeft een verbinding verbroken.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.<CheckUsabilityOnScavenge>g__ReadAheadWithZeroByteReadAsync|44_0()
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at RestSharp.RestClient.ThrowIfError(RestResponse response)
   at RestSharp.RestClient.ExecuteAsync(RestRequest request, CancellationToken cancellationToken)
   at RestSharp.RestClientExtensions.ExecuteAsync[T](RestClient client, RestRequest request, CancellationToken cancellationToken)
   at RestSharp.RestClientExtensions.GetAsync[T](RestClient client, RestRequest request, CancellationToken cancellationToken)
   at RaceControl.Services.F1TV.ApiService.QueryLiveSessionsAsync() in D:\Projects\RaceControl\RaceControl\Services\RaceControl.Services\F1TV\ApiService.cs:line 228
   at RaceControl.Services.F1TV.ApiService.GetLiveSessionsAsync() in D:\Projects\RaceControl\RaceControl\Services\RaceControl.Services\F1TV\ApiService.cs:line 71
   at RaceControl.ViewModels.MainWindowViewModel.RefreshLiveSessionsAsync(Boolean isFirstRefresh) in D:\Projects\RaceControl\RaceControl\RaceControl\ViewModels\MainWindowViewModel.cs:line 762
   at System.Threading.Tasks.TaskExtensions.Await(Task task, Action completedCallback, Action`1 errorCallback, Boolean configureAwait)
2022-04-24 18:30:10.1164 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?channelId=1033&contentId=1000005123'...
2022-04-24 18:31:36.2349 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?channelId=1033&contentId=1000005123'...
2022-04-24 18:32:39.6430 INFO Querying channels for session with UID '1000005116'...
2022-04-24 18:32:49.9112 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?channelId=1033&contentId=1000005116'...
2022-04-24 18:33:26.3845 INFO Querying channels for session with UID '1000005123'...
2022-04-24 18:33:51.0843 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?contentId=1000005123'...
2022-04-24 18:34:40.7854 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?contentId=1000005123'...
2022-04-24 18:35:08.2793 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?contentId=1000005123'...
2022-04-24 18:35:08.7270 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?contentId=1000005123'...
2022-04-24 18:38:08.6935 INFO Querying channels for session with UID '1000005293'...
2022-04-24 18:38:12.1495 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?contentId=1000005293'...
2022-04-24 18:38:30.2316 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?contentId=1000005293'...
2022-04-24 18:40:01.3945 INFO Querying channels for session with UID '1000005123'...
2022-04-24 18:40:58.7162 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?channelId=1033&contentId=1000005123'...
2022-04-24 18:41:59.5214 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?channelId=1033&contentId=1000005123'...
2022-04-24 18:45:41.8905 INFO Querying channels for session with UID '1000005116'...
2022-04-24 18:45:47.0032 INFO Querying channels for session with UID '1000005123'...
2022-04-24 18:48:59.8815 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?channelId=1033&contentId=1000005123'...
2022-04-24 20:00:07.3341 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?channelId=1033&contentId=1000005123'...
2022-04-24 20:53:43.1150 INFO Querying channels for session with UID '1000005293'...
2022-04-24 20:53:54.4473 INFO Getting tokenised URL for content-type 'Channel' and content-URL 'CONTENT/PLAY?contentId=1000005293'...

unquote

**Comment by sidewinder94** [comment]
Sounds like a duplicate of #413
