### ISSUE TITLE
[BUG] Value cannot be a null. (Parameter 'Source')

### ISSUE THREAD

**Issue by AmanAdusumilli** [robvdpol/RaceControl#460]
**Describe the bug**
When the Race Control app is opened a pop-up appears which says " Value cannot be a null. (Parameter 'Source') "

**To Reproduce**
Click on any season, race or any archive categories and this pop up will appear. Something which happens when you app or which you try to select something. the app was working a few mins before I started facing this issue. Tries restarting the app too.

**Screenshots**
here is a screenshot of the error/pop up - https://prnt.sc/AewJAVh_rf-n

**Desktop (please complete the following information):**
 - Windows edition and version
 - System type (32 or 64 bit)
 - Version (see title bar)

**F1TV account**
- Subscription type - PRO
- Country - USA
- Using VPN or proxy? - NO

**Additional context**

**Comment by AmanAdusumilli** [comment]
This is from the log, sending just in case if it can help you

2022-06-11 14:18:27.5148 ERROR A critical error occurred.
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at RaceControl.Services.F1TV.ApiService.GetEventsForSeasonAsync(Season season) in D:\Projects\RaceControl\RaceControl\Services\RaceControl.Services\F1TV\ApiService.cs:line 88
   at RaceControl.ViewModels.MainWindowViewModel.LoadEventsForSeasonAsync(Season season) in D:\Projects\RaceControl\RaceControl\RaceControl\ViewModels\MainWindowViewModel.cs:line 839
   at RaceControl.ViewModels.MainWindowViewModel.SelectSeasonAsync(Season season) in D:\Projects\RaceControl\RaceControl\RaceControl\ViewModels\MainWindowViewModel.cs:line 800
   at System.Threading.Tasks.TaskExtensions.Await(Task task, Action completedCallback, Action`1 errorCallback, Boolean configureAwait)

**Comment by oc-tk** [comment]
I have same problem + I cannot stream anything - green screen
