### ISSUE TITLE
[BUG] Unexpected error VideaoDialog

### ISSUE THREAD

**Issue by maxenfrance** [robvdpol/RaceControl#469]
**Describe the bug**
When trying to start a stream the error pups up and the stream doens't launch

**To Reproduce**
2. Play any stream

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/40918867/180596626-a65ca01f-9b94-460a-9b83-ba8cc568f504.png)

**Desktop (please complete the following information):**
 - Windows 11
 - System type (64 bit)
 - Version (2.6.4)

**F1TV account**
- Subscription type (Pro)
- Netherlands
- No VPN

**Comment by maxenfrance** [comment]
2022-07-23 10:28:09.4804 INFO No new release found.
2022-07-23 10:28:09.7969 INFO Querying events for season '2022 season'...
2022-07-23 10:28:09.8728 INFO Querying sessions for event with UID '1116'...
2022-07-23 10:28:09.8728 INFO Querying episodes for event with UID '1116'...
2022-07-23 10:28:11.3046 INFO Querying channels for session with UID '1000005171'...
2022-07-23 10:28:12.5607 ERROR An unhandled exception occurred.
Prism.Ioc.ContainerResolutionException: An unexpected error occurred while resolving 'System.Object', with the service name 'VideoDialog'
 ---> System.Windows.Markup.XamlParseException: Set property 'Prism.Mvvm.ViewModelLocator.AutoWireViewModel' threw an exception.
 ---> Prism.Ioc.ContainerResolutionException: An unexpected error occurred while resolving 'RaceControl.ViewModels.VideoDialogViewModel'
 ---> SharpGen.Runtime.SharpGenException: HRESULT: [0x88890001]
   at SharpGen.Runtime.Result.ThrowFailureException()
   at SharpGen.Runtime.Result.CheckError()
   at Vortice.XAudio2.IXAudio2.CreateMasteringVoice(Int32 inputChannels, Int32 inputSampleRate, Int32 flags, String szDeviceId, Nullable`1 effectChain, AudioStreamCategory streamCategory)
   at Vortice.XAudio2.IXAudio2.CreateMasteringVoice(Int32 inputChannels, Int32 inputSampleRate, AudioStreamCategory category, String deviceId, EffectDescriptor[] effectDescriptors)
   at FlyleafLib.MediaPlayer.Audio.Initialize(Int32 sampleRate)
   at FlyleafLib.MediaPlayer.Audio..ctor(Player player)
   at FlyleafLib.MediaPlayer.Player..ctor(Config config)
   at RaceControl.App.CreateFlyleafPlayer() in D:\Projects\RaceControl\RaceControl\RaceControl\App.xaml.cs:line 117
   at Prism.DryIoc.DryIocContainerExtension.<>c__DisplayClass23_0.<Register>b__0(IResolverContext r)
   at DryIoc.Registrator.<>c__DisplayClass49_0.<RegisterDelegate>b__0(IResolverContext r) in /_/src/DryIoc/Container.cs:line 7668
   at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 3118
   at DryIoc.Interpreter.TryInterpretMethodCall(IResolverContext r, Expression expr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 3414
   at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 3023
   at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 2942
   at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 3005
   at DryIoc.Interpreter.TryInterpretAndUnwrapContainerException(IResolverContext r, Expression expr, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 2864
   at DryIoc.Container.ResolveAndCache(Int32 serviceTypeHash, Type serviceType, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 409
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 356
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Type requiredServiceType, Request preResolveParent, Object[] args) in /_/src/DryIoc/Container.cs:line 428
   at DryIoc.Resolver.Resolve(IResolver resolver, Type serviceType, Object[] args, IfUnresolved ifUnresolved, Type requiredServiceType, Object serviceKey) in /_/src/DryIoc/Container.cs:line 8087
   at Prism.DryIoc.DryIocContainerExtension.Resolve(Type type, ValueTuple`2[] parameters)
   --- End of inner exception stack trace ---
   at Prism.DryIoc.DryIocContainerExtension.Resolve(Type type, ValueTuple`2[] parameters)
   at Prism.DryIoc.DryIocContainerExtension.Resolve(Type type)
   at Prism.PrismInitializationExtensions.<>c.<ConfigureViewModelLocator>b__0_0(Object view, Type type)
   at Prism.Mvvm.ViewModelLocationProvider.AutoWireViewModelChanged(Object view, Action`2 setDataContextCallback)
   at Prism.Mvvm.ViewModelLocator.AutoWireViewModelChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at System.Windows.Baml2006.WpfMemberInvoker.SetValue(Object instance, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at RaceControl.Views.VideoDialog.InitializeComponent() in D:\Projects\RaceControl\RaceControl\RaceControl\Views\VideoDialog.xaml:line 1
   at RaceControl.Views.VideoDialog..ctor() in D:\Projects\RaceControl\RaceControl\RaceControl\Views\VideoDialog.xaml.cs:line 7
   at DryIoc.Interpreter.TryInterpretAndUnwrapContainerException(IResolverContext r, Expression expr, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 2868
   at DryIoc.Container.ResolveAndCacheKeyed(Int32 serviceTypeHash, Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Object scopeName, Type requiredServiceType, Request preResolveParent, Object[] args) in /_/src/DryIoc/Container.cs:line 521
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Type requiredServiceType, Request preResolveParent, Object[] args) in /_/src/DryIoc/Container.cs:line 430
   at DryIoc.Resolver.Resolve(IResolver resolver, Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Type requiredServiceType, Object[] args) in /_/src/DryIoc/Container.cs:line 8070
   at Prism.DryIoc.DryIocContainerExtension.Resolve(Type type, String name, ValueTuple`2[] parameters)
   --- End of inner exception stack trace ---
   at Prism.DryIoc.DryIocContainerExtension.Resolve(Type type, String name, ValueTuple`2[] parameters)
   at Prism.DryIoc.DryIocContainerExtension.Resolve(Type type, String name)
   at Prism.Ioc.IContainerProviderExtensions.Resolve[T](IContainerProvider provider, String name)
   at Prism.Services.Dialogs.DialogService.ConfigureDialogWindowContent(String dialogName, IDialogWindow window, IDialogParameters parameters)
   at Prism.Services.Dialogs.DialogService.ShowDialogInternal(String name, IDialogParameters parameters, Action`1 callback, Boolean isModal, String windowName)
   at Prism.Services.Dialogs.DialogService.Show(String name, IDialogParameters parameters, Action`1 callback, String windowName)
   at RaceControl.ViewModels.MainWindowViewModel.WatchContent(IPlayableContent playableContent, VideoDialogSettings settings) in D:\Projects\RaceControl\RaceControl\RaceControl\ViewModels\MainWindowViewModel.cs:line 884
   at RaceControl.ViewModels.MainWindowViewModel.WatchContentExecute(IPlayableContent playableContent) in D:\Projects\RaceControl\RaceControl\RaceControl\ViewModels\MainWindowViewModel.cs:line 390
   at Prism.Commands.DelegateCommand`1.Execute(T parameter)
   at Prism.Commands.DelegateCommand`1.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
