### ISSUE TITLE
Cant watch or download anything

### ISSUE THREAD

**Issue by hypoflex** [robvdpol/RaceControl#47]
tried watching and downloading highlight of 2021, a race of 2020, and worldfeed all giving the same errors

![image](https://user-images.githubusercontent.com/36196198/111211749-13b0a400-85cf-11eb-9e52-189c0d545e34.png)

snippet of the log:

> 2021-03-15 20:44:59.4124 ERROR [VLC] cannot initialize COM (error 0x80010106)
2021-03-15 20:44:59.4124 INFO Getting tokenised URL for content-type 'Asset' and content-URL 'CONTENT/PLAY?contentId=1000001387'...
2021-03-15 20:44:59.7221 WARN A non-critical error occurred.
System.ArgumentNullException: Value cannot be null. (Parameter 'mrl')
   at LibVLCSharp.Shared.Media.SelectNativeCtor(LibVLC libVLC, String mrl, FromType type)
   at LibVLCSharp.Shared.Media.<>c__DisplayClass2_0.<.ctor>b__0()
   at LibVLCSharp.Shared.Internal..ctor(Func`1 create, Action`1 release)
   at LibVLCSharp.Shared.Media..ctor(Func`1 create, Action`1 release, String[] options)
   at LibVLCSharp.Shared.Media..ctor(LibVLC libVLC, String mrl, FromType type, String[] options)
   at RaceControl.Vlc.VlcMediaDownloader.StartDownloadAsync(String streamUrl, String filename) in D:\Projects\RaceControl\RaceControl\RaceControl\Vlc\VlcMediaDownloader.cs:line 45
   at RaceControl.ViewModels.DownloadDialogViewModel.GetTokenisedUrlAndStartDownloadAsync(String subscriptionToken) in D:\Projects\RaceControl\RaceControl\RaceControl\ViewModels\DownloadDialogViewModel.cs:line 68
   at System.Threading.Tasks.TaskExtensions.Await(Task task, Action completedCallback, Action`1 errorCallback, Boolean configureAwait)
2021-03-15 20:45:01.8877 ERROR [VLC] cannot initialize COM (error 0x80010106)
2021-03-15 20:45:01.8877 INFO Getting tokenised URL for content-type 'Asset' and content-URL 'CONTENT/PLAY?contentId=1000001387'...
2021-03-15 20:45:01.9531 ERROR A critical error occurred.
System.ArgumentNullException: Value cannot be null. (Parameter 'mrl')
   at LibVLCSharp.Shared.Media.SelectNativeCtor(LibVLC libVLC, String mrl, FromType type)
   at LibVLCSharp.Shared.Media.<>c__DisplayClass2_0.<.ctor>b__0()
   at LibVLCSharp.Shared.Internal..ctor(Func`1 create, Action`1 release)
   at LibVLCSharp.Shared.Media..ctor(Func`1 create, Action`1 release, String[] options)
   at LibVLCSharp.Shared.Media..ctor(LibVLC libVLC, String mrl, FromType type, String[] options)
   at RaceControl.Vlc.VlcMediaPlayer.StartPlaybackAsync(String streamUrl) in D:\Projects\RaceControl\RaceControl\RaceControl\Vlc\VlcMediaPlayer.cs:line 106
   at RaceControl.ViewModels.VideoDialogViewModel.StartStreamAsync() in D:\Projects\RaceControl\RaceControl\RaceControl\ViewModels\VideoDialogViewModel.cs:line 437
   at RaceControl.ViewModels.VideoDialogViewModel.InitializeAsync() in D:\Projects\RaceControl\RaceControl\RaceControl\ViewModels\VideoDialogViewModel.cs:line 408
   at System.Threading.Tasks.TaskExtensions.Await(Task task, Action completedCallback, Action`1 errorCallback, Boolean configureAwait)

**Comment by rubengarciavilches** [comment]
I cannot watch any of the Press conferences of the pre season testing, Tech talk and Highlights work perfectly.
For 2020 I can only watch Pre Season and 9 Grand Prix, of whom I can only watch practice and Qualifying, no race.

**Comment by ottonello** [comment]
@hypoflex make sure your account is active! I was logging in using the wrong account, a formula1.com account without f1tv.

**Comment by hypoflex** [comment]
> @hypoflex make sure your account is active! I was logging in using the wrong account, a formula1.com account without f1tv.

yea, i eventually figured out thhat something went wrong with the subscription since i pay using apple appstore, i was able to watchh fine on my phone but on the ddesktop website it kept saying i didnt have a subscription.

guess something with the new season went wrong.

i eventually fixed it by cancelling my sub through appstore and reactivating it in the app.
sadly i payed extra for that bug.
