### ISSUE TITLE
[BUG] Value cannot be null. (Parameter 'source') when switching between casting devices.

### ISSUE THREAD

**Issue by schumi2004** [robvdpol/RaceControl#83]
**Describe the bug**
When searching for casting devices and switching between them i'm getting an error:
Value cannot be null. (Parameter 'source')

**To Reproduce**
1. Go to 'Chromecast'
2. Scan for devices
3. Select 1 from pull down menu.
4. I'm getting the error for Philips Android TV's only, not for MiBox's or Nvidia Shield's

**Expected behavior**
No error at all.

**Screenshots**

![2021-04-16 152057](https://user-images.githubusercontent.com/968545/115030464-6aa7e280-9ec7-11eb-895e-1de17f5855c1.jpg)

**Desktop (please complete the following information):**
 - Windows 10 Pro
 - 64 bit
 - Version 2.0.4 (also seen it in previous versions)

**F1TV account**
- Subscription type: Pro
- Country: NL
- Using VPN or proxy?: n/a

**Additional context**
TV Model: Philips 49PUS6412
Android version: 8.0.0

**Comment by robvdpol** [comment]
Do you get the error when switching between devices, or when starting the casting?

**Comment by schumi2004** [comment]
When switching.
Casting itself seems to work fine.

**Comment by LoVega1337** [comment]
Adding to this, I also get this error message when I'm solely scanning for devices _and_ switching devices. Although, like @schumi2004 said, casting works fine.

**Comment by bartdevriendt** [comment]
I had this problem today as well while I was testing my PR.  It happens when scanning for devices and searching for audio tracks.  This is the underlying stack trace:

   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at GoogleCast.Channels.ReceiverChannel.<EnsureConnectionAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GoogleCast.Channels.MediaChannel.<SendAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RaceControl.ViewModels.MainWindowViewModel.<FindAudioTracksAsync>d__227.MoveNext() in E:\Projecten\Dotnet\RaceControl\RaceControl\RaceControl\ViewModels\MainWindowViewModel.cs:line 992
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskExtensions.<Await>d__5.MoveNext()

Line 992 is :

var status = await mediaChannel.GetStatusAsync() in the FindAudioTracksAsync method

**Comment by robvdpol** [comment]
I added some error handling for this. Might be caused by a bug in Googlecast or compatibility issues of some Chromecast devices.
