### ISSUE TITLE
[BUG] Internal Player won't start

### ISSUE THREAD

**Issue by MasoLinguist** [robvdpol/RaceControl#99]
**Describe the bug**
If I hit the "watch" button I'll get two error messages

**To Reproduce**
1. Go to some session
2. Play stream world feed
3. Press button watch

**Expected behavior**
Stream should start in an player window
**Screenshots**
![msg_1](https://user-images.githubusercontent.com/12135211/116680239-ba98a600-a9ab-11eb-93aa-6da61f00d7ed.PNG)
![msg_2](https://user-images.githubusercontent.com/12135211/116680254-bd939680-a9ab-11eb-973c-ac2a09f01eb1.PNG)

**Desktop (please complete the following information):**
 - Windows 8.1 professional
 - System type 64 bit
 - Version 2.1.0

**F1TV account**
- Pro
- NL but steaming in Germany
- No vpn no proxy

**Additional context**
Same version works fine with my Win10 machine.

**Comment by michielcox** [comment]
Same here

**Comment by robvdpol** [comment]
Could you paste relevant log file entries? Log file is located in %LOCALAPPDATA%\RaceControl

**Comment by MasoLinguist** [comment]
> Could you paste relevant log file entries? Log file is located in %LOCALAPPDATA%\RaceControl

Here you go. Thank your time. :+1: 

```
2021-04-30 11:56:47.3524 ERROR An unhandled exception occurred.
SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: Falscher Parameter.

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateDevice(Adapter adapter, DriverType driverType, DeviceCreationFlags flags, FeatureLevel[] featureLevels)
   at FlyleafLib.MediaRenderer.Renderer..ctor(Player player)
   at FlyleafLib.MediaPlayer.Player.InitializeControl2(Flyleaf newValue)
   at FlyleafLib.MediaPlayer.Player.InitializeControl1(Flyleaf oldValue, Flyleaf newValue)
   at FlyleafLib.MediaPlayer.Player.set_Control(Flyleaf value)
   at FlyleafLib.Controls.WPF.VideoView.OnApplyTemplate()
   at System.Windows.FrameworkElement.ApplyTemplate()
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Border.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Control.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Decorator.MeasureOverride(Size constraint)
   at System.Windows.Documents.AdornerDecorator.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Border.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Window.MeasureOverrideHelper(Size constraint)
   at System.Windows.Window.MeasureOverride(Size availableSize)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Interop.HwndSource.set_RootVisual(Visual value)
   at System.Windows.Window.SetRootVisual()
   at System.Windows.Window.SetRootVisualAndUpdateSTC()
   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.CreateSourceWindowDuringShow()
   at System.Windows.Window.SafeCreateWindowDuringShow()
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at RaceControl.Views.VideoDialogWindow.Prism.Services.Dialogs.IDialogWindow.Show()
   at Prism.Services.Dialogs.DialogService.ShowDialogWindow(IDialogWindow dialogWindow, Boolean isModal)
   at Prism.Services.Dialogs.DialogService.ShowDialogInternal(String name, IDialogParameters parameters, Action`1 callback, Boolean isModal, String windowName)
   at Prism.Services.Dialogs.DialogService.Show(String name, IDialogParameters parameters, Action`1 callback, String windowName)
   at RaceControl.ViewModels.MainWindowViewModel.WatchContent(IPlayableContent playableContent, VideoDialogSettings settings) in D:\Projects\RaceControl\RaceControl\RaceControl\ViewModels\MainWindowViewModel.cs:line 809
   at RaceControl.ViewModels.MainWindowViewModel.WatchContentExecute(IPlayableContent playableContent) in D:\Projects\RaceControl\RaceControl\RaceControl\ViewModels\MainWindowViewModel.cs:line 369
   at Prism.Commands.DelegateCommand`1.Execute(T parameter)
   at Prism.Commands.DelegateCommand`1.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2021-04-30 11:56:47.4820 ERROR An unhandled exception occurred.
System.NullReferenceException: Object reference not set to an instance of an object.
   at FlyleafLib.MediaFramework.DecoderContext.Pause()
   at FlyleafLib.MediaPlayer.Player.Initialize()
   at FlyleafLib.MediaPlayer.Player.Stop()
   at RaceControl.Flyleaf.FlyleafMediaPlayer.StopPlayback() in D:\Projects\RaceControl\RaceControl\RaceControl\Flyleaf\FlyleafMediaPlayer.cs:line 141
   at RaceControl.ViewModels.VideoDialogViewModel.OnDialogClosed() in D:\Projects\RaceControl\RaceControl\RaceControl\ViewModels\VideoDialogViewModel.cs:line 159
   at Prism.Services.Dialogs.DialogService.<>c__DisplayClass10_0.<ConfigureDialogWindowEvents>b__3(Object o, EventArgs e)
   at System.Windows.Window.OnClosed(EventArgs e)
   at System.Windows.Window.WmDestroy()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2021-04-30 11:57:29.4737 INFO Refreshing live sessions...
2021-04-30 11:57:29.4737 INFO Querying live sessions...
2021-04-30 11:58:00.0531 ERROR A critical error occurred.
System.NullReferenceException: Object reference not set to an instance of an object.
   at FlyleafLib.MediaFramework.DecoderContext.Pause()
   at FlyleafLib.MediaPlayer.Player.Initialize()
   at FlyleafLib.MediaPlayer.Player.Open(String url)
   at RaceControl.Flyleaf.FlyleafMediaPlayer.StartPlayback(String streamUrl, VideoDialogSettings settings) in D:\Projects\RaceControl\RaceControl\RaceControl\Flyleaf\FlyleafMediaPlayer.cs:line 136
   at RaceControl.ViewModels.VideoDialogViewModel.StartStreamAsync() in D:\Projects\RaceControl\RaceControl\RaceControl\ViewModels\VideoDialogViewModel.cs:line 475
   at RaceControl.ViewModels.VideoDialogViewModel.InitializeAsync() in D:\Projects\RaceControl\RaceControl\RaceControl\ViewModels\VideoDialogViewModel.cs:line 449
   at System.Threading.Tasks.TaskExtensions.Await(Task task, Action completedCallback, Action`1 errorCallback, Boolean configureAwait)
```

**Comment by robvdpol** [comment]
> Same here

Which version of Windows are you using?

**Comment by robvdpol** [comment]
Probably fixed in next release.
